import type { NextPage } from 'next';
import Head from 'next/head';

import { HeaderTop } from '../mocks/headerTop';
import { Header } from '../mocks/header';

import Layout from '../components/Layout';

import Banner from '../components/Banner';
import About from '../components/About';
import TodayAmazon from '../components/TodayAmazon';
import OurProjects from '../components/OurProjects';

const Home: NextPage = ({ headerTop, header }: any) => {

  return (
    <Layout data={{ header, headerTop }}>
      <Head>
        <title>MyAmazon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <About />
      <TodayAmazon />
      <OurProjects />
    </Layout>
  )
}

export const getStaticProps = ({ locale }: any) => {

  if (locale === 'en') {
    return {
      props: {
        headerTop: HeaderTop.en,
        header: Header.en
      }
    }
  }

  return {
    props: {
      headerTop: HeaderTop.pt,
      header: Header.pt
    }
  }
}

export default Home;